// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWLQotgMTpOYpitxYZ1PKlo_WYZMXtJN0',
    appId: '1:611741077092:web:1a0b4785dfe6778dec1971',
    messagingSenderId: '611741077092',
    projectId: 'apis-743a8',
    authDomain: 'apis-743a8.firebaseapp.com',
    storageBucket: 'apis-743a8.firebasestorage.app',
    measurementId: 'G-8C7FL9SNGZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDeTPwxKkmJP0siiumlMdzl7xMezUfKb6Q',
    appId: '1:611741077092:android:48ab980f0b03ecc5ec1971',
    messagingSenderId: '611741077092',
    projectId: 'apis-743a8',
    storageBucket: 'apis-743a8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDn_50yGLXOTgb9YyzE09xvS8UvsUaMvdA',
    appId: '1:611741077092:ios:e7f8ca767a20be9bec1971',
    messagingSenderId: '611741077092',
    projectId: 'apis-743a8',
    storageBucket: 'apis-743a8.firebasestorage.app',
    iosClientId:
        '611741077092-a94bciaarupcb3mhsmqvjsivjboeds80.apps.googleusercontent.com',
    iosBundleId: 'com.example.sututehApp',
  );
}
